services:

#postgres db
  db:
    image: postgres:latest
    container_name: postgres_quotes
    restart: always
    environment:
      POSTGRES_USER: quoteuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: quotes
    volumes:
      - ./backend/postgres_init:/docker-entrypoint-initdb.d:Z
    ports:
      - "5432:5432"

  api:
    image: node:20-slim
    container_name: api_quotes
    working_dir: /app
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/app:z
      - /app/node_modules
    command: sh -c "npm install && npm start"

# frontend angular (dev)
  frontend:
    image: node:20-slim
    container_name: frontend_quotes
    ports:
      - "4200:4200"
    depends_on:
      - api
    working_dir: /app
    volumes: 
      - ./frontend:/app:Z
      - /app/node_modules
    command: sh -c "npm install && npm start"

# frontend angular (production)
#frontend:
#  image: nginx:latest
#  container_name: frontend_quotes
#  ports:
#    - "80:80"
#  volumes:
#    - ./frontend/dist/frontend:/usr/share/nginx/html:Z
