services:

#postgres db
  db:
    image: postgres:latest
    container_name: postgres_quotes
    restart: always
    environment:
      POSTGRES_USER: quoteuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: quotes
    volumes:
      - ./backend/postgres_init:/docker-entrypoint-initdb.d:Z
    ports:
      - "5432:5432"

# api 
  api:
      build: ./backend
      container_name: api_quotes
      ports:
        - "3000:3000"
      depends_on:
        - db
      volumes:
        - ./backend:/app:Z

# frontend angular 
  nginx:
    image: nginx:latest
    container_name: frontend_quotes
    ports:
      - "80:80"
    depends_on:
      - api
    volumes: 
      - ./frontend:/app:Z
    command: "sh -c npm install && npm run dev"
    user: "root"
